server: 
   port: 8081

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/filmbuff
      username: root
      password: password
   application:
      name: Filmbuff
logging: 
   level: 
      com:
         mycompany:
            filmbuff: debug
   file:
      path: /var/log/filmbuff.log


